name = "Ghostbasil"
uuid = "42a9b20f-2d23-465a-b7ed-975dbff4a4d6"
authors = ["Benjamin Chu <benchu99@hotmail.com> and contributors"]
version = "0.0.1"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
ghostbasil_jll = "caeec347-1c5e-53ac-8e86-7f5e1a690164"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
CxxWrap = "0.14.2"
ghostbasil_jll = "0.0.15"
libcxxwrap_julia_jll = "0.11.2" # 0.12 is not working as of 1.24.2024
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
