name = "ghostbasil"
uuid = "42a9b20f-2d23-465a-b7ed-975dbff4a4d6"
authors = ["Benjamin Chu <benchu99@hotmail.com> and contributors"]
version = "0.0.1"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
ghostbasil_jll = "caeec347-1c5e-53ac-8e86-7f5e1a690164"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
